version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: helpdesk_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8005:8000
    env_file:
      - .env

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: helpdesk_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: helpdesk_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - flower

  flower:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: helpdesk_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - celery_worker