#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# uvicorn main:app --reload --reload-dir project --host 0.0.0.0
# gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --chdir=/app
hypercorn main:app --bind 0.0.0.0:8000
