#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

uvicorn main:app --workers 1 --host 0.0.0.0 --port 8000 --log-level debug --timeout-keep-alive 86400 --ping-interval 86400
# gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --chdir=/app
# hypercorn --config main:app --bind 0.0.0.0:8000 --chdir=/app
# daphne -b 0.0.0.0 -p 8000 main:app --websocket_timeout -1 --websocket_connect_timeout -1