# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  cd-pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_CREDENTIAL_HOSTNAME }}
          username: ${{ secrets.SERVER_CREDENTIAL_USERNAME }}
          key: ${{ secrets.SERVER_CREDENTIAL_PRIVATE_KEY }}
          port: 2211
          script_stop: true
          debug: true
          script: |
            cd /home/rezayogaswara/python_projects/helpdesk-router
            pwd
            ls -ahl
            echo ----------------------------------------------
            git pull origin main
            echo ----------------------------------------------
            docker-compose down -v
            echo ----------------------------------------------
            docker-compose up -d --build
            echo ----------------------------------------------
            service nginx restart
            echo ----------------------------------------------